osx_image: xcode9.3
language:  objective-c 
before_install:
    - gem install xcpretty
before_script:
    - set -o pipefail 
script:
    - xcodebuild test -project ./Aisatsu.xcodeproj -scheme AisatsuTests -configurarion Debug | xcpretty -c # xcodebuild build & test
